num_hand: 5
num_deck:
  min: 40
  max: 60
condition:
  - name: Gamma
    min: 3
    max: 3
    require: 1
    exact: False
    in_hand: True
  - name: Driver
    min: 1
    max: 1
    require: 1
    exact: True
    in_hand: False
